# For more info on HTTP files go to https://aka.ms/vs/httpfile

@schema=https
@hostname=localhost
@port=7215

GET {{schema}}://{{hostname}}:{{port}}/api/cities

###
GET {{schema}}://{{hostname}}:{{port}}/api/cities
Accept:application/json

###
POST {{schema}}://{{hostname}}:{{port}}/api/cities/1/pointsofinterest
Accept:application/json
Content-Type:application/json

{
    "name": "a name for testing",
    "description": "A description for testing"
}
